<link type="image/png" sizes="16x16" href="<?php echo base_url();?>images/logo/logo.png">
<title>IPRO3D-Services</title>

<body background="<?php echo base_url();?>assets/images/slider/img1.jpg">

<div class="row">
    <div class="col-md-2 col-xlg-3">

        <a href="#1" class="list-group-item">
            <b class="text font-weight-bold text-danger">Email : hello@ipro3d.io
                <br>
                Mobile No. : 9821413663</b>
        </a>
        <br>
        <a href="#1" class="list-group-item">
            <b class="text font-weight-bold text-primary">Testimonial</b>
            <p class="text">Ipro3d blog read more..</p>
        </a>


    </div>

    <div class="col-md-8 col-xlg-6">


<div class="card">
                        <div class="card-body" style="background-color:#F5F5F5;">
                            <h2 class="card-title" id="printing" align="center" style="font-weight: bold;font-family: Philosiphers">1. 3D Printing</h2>
                            <img src="<?php echo base_url();?>assets/images/slider/img5.jpg" height="400px" width="100%" align="center"><br><br>
                            <p class="text font-normal;" style="text-align: justify;">   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Technology has made everything simple and easy to understand. Explore the new standerds in 3d printing industry. If you want to make an actual prototype (3d physical object/part) of your 3d CAD model file, IPRO3D is the right place which offers authentic materials and processes for 3d printing models/designs. We make sure that everything you get is of excellent qualityWhat is 3d printing? Glad you asked.
                Additive manufacturing process is popularly known as 3d printing. Additive manufacturing is a method of manufacturing physical parts in a successive addition process of adding material layer by layer but only one layer at a time on top of each other layer to build a physical part from a digital 3d CAD file.  The additive manufacturing principal is totally opposite to the traditional subtractive manufacturing using lathes, CNC’s, mills, etc.
                </br></br>Additive manufacturing has several different methods/processes of producing a prototype. Although each method/process has its own advantages but the principle of additive manufacturing or the popularly known name 3d printing remains the same.
                The Idea of building a physical part by adding material rather than cutting away material applies no matter whichever additive manufacturing process you choose to use.
                Step one
                First of all you will need an .STL file to upload. This file is generated by exporting or by saving you digital 3d CAD model in STL format. This file is a digital file of your 3d CAD model that you want to get 3d printed as a physical 3d object/part. Don’t worry isn’t as scary as it sounds.
                </br></br>

                <div class="row">
                  <div class="col-md-4">
                      <img src="<?php echo base_url();?>assets/images/slider/img4.jpg"  height="200px" width="250px"/>
                      <div><br></div>
                  </div>
                  <div class="col-md-4">
                      <img src="<?php echo base_url();?>assets/images/slider/img1.jpg"  height="200px" width="250px"/>
                      <div><br></div>
                  </div>
                  <div class="col-md-4">
                      <img src="<?php echo base_url();?>assets/images/slider/img7.jpg"  height="200px" width="250px"/>
                      <div><br></div>
                  </div>
              </div><br>
              <br>
               These are several other ways to get 3d models</br>
               <ul>
                   <li>3D scans your object: 3d scanning is not an easy process and generally requires a professional with 3d scanning equipment.</li>
                   <li>CAD software: Computer Aided Design (CAD) has come a long way and has developed drastically which made it very much easy for you to 3d model/design your parts yourself.</li>
                   <li>Download free designs: you can download free designs online IPRO3D marketplace offers free and paid designs for 3d printing and get it 3d printed from IPRO3D.</li>
                 <li>   Hire an expert designer:  If you don’t know 3d CAD designing/modeling or  require your design to be taken to next level, you can choose one of our Indian IPRO3D member expert designer to 3d CAD design/model your idea and make it ready for 3d printing.</li>
               </ul></p>
               </br></br><br><br>
                </div>
        </div><br>
</div>


<div class="col-md-2 col-xlg-3">

    <a href="#1" class="list-group-item">
        <b class="text font-weight-bold text-primary">Blog</b>
        <p class="text">Ipro3d blog read more..</p>
    </a>
    <br>

</div>
</div>
<hr>
    <div class="container">
        <div class="row" align="center">
            <div class="col-md-3" >
            </div>
            <div class="col-md-6" >
                <div class="thumbnail center well well-sm text-center">
                    <h2>Newsletter</h2> 
                    <p>Subscribe to our weekly Newsletter and stay tuned.</p>
                    <form action="" method="post" role="form">
                        <div class="input-group">
                          <span class="input-group-text">
                            <i class="fa fa-envelope"></i>
                          </span>
                          <input class="form-control" type="text" id="" name="" placeholder="your@email.com">
                        </div><br>
                        <input type="submit" value="Subscribe" class="btn btn-large btn-primary" />
                  </form>
                </div>    
            </div>
        </div><br>
    </div>

<script src="<?php echo base_url()."style/full/assets/plugins/jquery/jquery.min.js";?>"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="<?php echo base_url()."style/full/assets/plugins/popper/popper.min.js";?>"></script>
<script src="<?php echo base_url()."style/full/assets/plugins/bootstrap/js/bootstrap.min.js";?>"></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src="<?php echo base_url()."style/full/js/jquery.slimscroll.js"?>"></script>
<!--Wave Effects -->
<script src="<?php echo base_url()."style/full/js/waves.js"?>"></script>
<!--Menu sidebar -->
<script src="<?php echo base_url()."style/full/js/sidebarmenu.js"?>"></script>
<!--stickey kit -->
<script src="<?php echo base_url()."style/full/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js";?>"></script>
<script src="<?php echo base_url()."style/full/assets/plugins/sparkline/jquery.sparkline.min.js"?>"></script>
<!--Custom JavaScript -->
<script src="<?php echo base_url()."style/full/js/custom.min.js"?>"></script>
</body>                
